// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// task "graphqlEndpoint": "https://co5rogzxbbcitfrlij3o4ec2zy.appsync-api.us-east-1.amazonaws.com/graphql",
//https://py7l3esqjfcddi2q4c5l7bofpi.appsync-api.us-east-1.amazonaws.com/graphql


export default {
   // "graphqlEndpoint": "https://co5rogzxbbcitfrlij3o4ec2zy.appsync-api.us-east-1.amazonaws.com/graphql",
   // "region": "us-east-1",
   // "authenticationType": "API_KEY",
  //  "apiKey": "da2-tywdh2ol7zcxpmv73wfbzjbli4",
  "graphqlEndpoint": "https://hwi3yjkvp5cnddqdsmest7kdjm.appsync-api.us-east-2.amazonaws.com/graphql",
  "region": "us-east-2",
  "authenticationType": "API_KEY",
  "apiKey": "da2-pz6nfraembd4fclouitwfsjh6q",
}