// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    "graphqlEndpoint": "https://co5rogzxbbcitfrlij3o4ec2zy.appsync-api.us-east-1.amazonaws.com/graphql",
    "region": "us-east-1",
    "authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "apiKey": "da2-tywdh2ol7zcxpmv73wfbzjbli4",
}